# Generated by Django 4.2.1 on 2023-05-31 22:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0003_rename_list_todoitem_todo_list_list_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todoitem",
            name="due_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
