# Generated by Django 4.2.1 on 2023-05-31 23:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0004_alter_todoitem_due_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="todoitem",
            options={"ordering": ["task"]},
        ),
    ]
